# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: geoconnex.us Guidebook
author: Internet of Water Coalition
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/internetofwater/docs.geoconnex.us  # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: "./_static/img/favicon.ico"
  use_issues_button: true
  use_repository_button: true
  announcement: "Under Construction"
  comments:
    hypothesis: true
  extra_navbar: Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
  extra_footer: |  # Will be displayed underneath the footer.
    <div class="container-lg mt-3">
      <div class="row">
        <div class="col-xl-3">
            <div class="footerImages">
              <a href="https://europa.eu/"><img src="../../../_static/images/logo/eu-flag.png" height="20" alt="EU flag" style="float:center""></a>
              <a href="https://www.imi.europa.eu/"><img src="../../../_static/images/logo/imi-logo.png" height="20" alt="IMI logo" style="float:center""></a>
              <a href="https://efpia.eu"><img src="../../../_static/images/logo/efpia-logo.png" height="20" alt="EFPIA logo" style="float:center""></a>
            </div>
            <div class="mb-3"> Grant agreement 802750 </div>
        </div>
        <div class="col-xl-6 d-flex">
          <div class="container">
            <div class="row">
              <div class="col-6 d-flex" style="justify-content:center">
                <ul>
                  <li><a href="mailto:fairplus-cookbook@elixir-europe.org"> Contact us </a></li>
                  <li><a href="https://fairplus-project.eu" target="_blank"> FAIRplus </a> </li>
                </ul>
              </div>
              <div class="col-6 d-flex" style="justify-content:center">
                <ul>
                  <li> <a href="https://faircookbook.elixir-europe.org/content/recipes/boilerplate/people.html  "> Contributors </a> </li> </li>
                  <li> <a href="https://faircookbook.elixir-europe.org/content/recipes/help.html"> How to contribute </a> </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xl-3">
          <a href="https://geoconnex.us/" target="_blank"><img src="../../../_static/img/geoconnex-logo.png" height="150" alt="geoconnex logo" style="float:center""></a>
        </div>
      </div>
    </div>
    <div class="row_footer my-3">
      The geoconnex.us Guidebook and Knowledge Graph are licensed under the <a href="https://creativecommons.org/publicdomain/zero/1.0/" target="_blank"><img src="http://i.creativecommons.org/p/zero/1.0/88x31.png" style="border-style: none;" alt="CC0" />Creative Commons Zero 1.0</a> (CC0) license.
    </div>"
