# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Guidebook
author: the Internet of Water Coalition
logo: _static/img/geoconnex-logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/internetofwater/docs.geoconnex.us  # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: "./_static/img/favicon.ico"
  use_issues_button: true
  use_repository_button: true
#  use_multitoc_numbering: false
  announcement: "Under Construction"
  comments:
    hypothesis: true
  extra_navbar: Powered by <a href="https://jupyterbook.org">Jupyter Book</a>   # Will be displayed underneath the left navbar.
  extra_footer: |  # Will be displayed underneath the footer.
    <div class="container-lg mt-3">
      <div class="row">
        <div class="col-xl-3">
            <div class="footerImages">
              <a href="http://cgs.earth/"><img src="../../../_static/img/cgs-logo2.png" height="70" alt="CGS" style="float:center""></a>
              <a href="https://nicholasinstitute.duke.edu/"><img src="../../../_static/img/duke-logo.png" height="70" alt="Duke logo" style="float:center""></a>
              <a href="https://usgs.gov"><img src="../../../_static/img/usgs.png" height="70" alt="USGS logo" style="float:center""></a>
            </div>
        </div>
        <div class="col-xl-6 d-flex">
          <div class="container">
            <div class="row">
              <div class="col-6 d-flex" style="justify-content:center">
                <ul>
                  <li><a href="mailto:konda@lincolninst.edu"> Contact us </a></li>
                  <li><a href="http://cgs.earth" target="_blank"> Center for Geospatial Solutions </a> </li>
                  <li><a href="https://internetofwater.org" target="_blank"> Internet of Water Coalition </a> </li>
                </ul>
              </div>
              <div class="col-6 d-flex" style="justify-content:center">
                <ul>
                  <li> <a href="https://faircookbook.elixir-europe.org/content/recipes/boilerplate/people.html  "> Contributors </a> </li> </li>
                  <li> <a href="https://faircookbook.elixir-europe.org/content/recipes/help.html"> How to contribute </a> </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xl-3">
           <a href="https://internetofwater.org/" target="_blank"><img src="../../../_static/img/iow-project.png" height="200" width="138" alt="iow logo" style="float:center""></a>
        </div>
      </div>
    </div>
    <div class="row_footer my-3">
      The geoconnex.us Guidebook and Knowledge Graph are licensed under the <a href="https://creativecommons.org/publicdomain/zero/1.0/" target="_blank"><img src="http://i.creativecommons.org/p/zero/1.0/88x31.png" style="border-style: none;" alt="CC0" />Creative Commons Zero 1.0</a> (CC0) license. This material is based upon work supported by the U.S. Geological Survey under Grant Nos. G21AP10607 and G21AC10732
    </div>
